version: '3'

services:
  app-node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: bmannramos/app-node:prod
    container_name: app-node
    volumes:
      - ./node:/usr/src/app
    tty: true
    entrypoint:  node index.js
    ports:
      - "3000:3000"
    networks:
      - desafio-nginx
    depends_on:
      - app-db
      
  app-db:
    image: mysql:latest
    user: "mysql:mysql"
    restart: always
    # command: --innodb-use-native-aio=0
    # command: ["--init-file", "/docker-entrypoint-initdb.d/init_script.sh"]
    command: --default-authentication-plugin=mysql_native_password
    container_name: app-db
    tty: true
    # entrypoint:  mysqld --init-file=/docker-entrypoint-initdb.d/dump.sql --user=root
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_ROOT_HOST = '%'

    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      # - ./dump/init_container.sh:/docker-entrypoint-initdb.d/init_container.sh
      # command: ["--init-file", "/docker-entrypoint-initdb.d/init_container.sh"]
    networks:
      - desafio-nginx

  app-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: bmannramos/app-nginx:prod
    container_name: app-nginx
    tty: true
    ports:
      - "8080:80"
    networks:
      - desafio-nginx
    depends_on:
      - app-node
        
networks:
  desafio-nginx:
    driver: bridge