version: '3'

services:
  app-node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: bmannramos/app-node:prod
    container_name: app-node
    user: "root:root"
    volumes:
        - ./node:/usr/src/app
        - ./node/node_modules:/usr/src/app/node_modules
    tty: true
    entrypoint: 
    command: sh -c "yarn install && node /usr/src/app/index.js"
    ports:
      - "3000:3000"
    networks:
      - desafio-nginx
    depends_on:
      - app-db
      
  app-db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: app-db
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_ROOT_HOST = '%'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - desafio-nginx

  app-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: bmannramos/app-nginx:prod
    container_name: app-nginx
    tty: true
    ports:
      - "8080:80"
    networks:
      - desafio-nginx
    depends_on:
      - app-node
        
networks:
  desafio-nginx:
    driver: bridge